### ISSUE TITLE
Create a registration page for the application

### ISSUE THREAD

**Issue by ankitshaw** [CodingIndia/travel-safe#10]

**Comment by Rukmini-Meda** [comment]
I am interested to work on this issue.

**Comment by akshaydhiran** [comment]
I want to work on this issue.

**Comment by ankitshaw** [comment]
@Rukmini-Meda you have been assigned the issue.

**Comment by Rukmini-Meda** [comment]
Thanks! I will update my work progress.

**Comment by FrozenGirl-spd** [comment]
Can i work on the issue?

**Comment by SnegaRamesh** [comment]
I would like to work on this issue.

**Comment by ankitshaw** [comment]
@Rukmini-Meda  are you still working on it, need any help?

**Comment by Rukmini-Meda** [comment]
Yes sir, I am working on it. I will make the PR today. Sorry for being late.

**Comment by ankitshaw** [comment]
no issue.

**Comment by FrozenGirl-spd** [comment]
Can i work on the issue?
@ankitshaw

**Comment by Rukmini-Meda** [comment]
@ankitshaw I am working on this issue. Please respond to my messages on slack. I have doubts. Once it's clear, I can make PR immediately.

**Comment by ankitshaw** [comment]
I have replied. You can raise your doubt here as well

**Comment by Rukmini-Meda** [comment]
Okay, I will make a PR by tonight and will ask doubts if any.
