### ISSUE TITLE
Add a location share button

### ISSUE THREAD

**Issue by ankitshaw** [CodingIndia/travel-safe#12]
You need to add a location share button that will share the current location of the user to external apps like messenger, whatsapp etc.

**Comment by sanxy** [comment]
I will like to take this issue

**Comment by myselfanuj** [comment]
I would like to work on it. I already implemented this feature in my project"WiLdCare". Please assign me this issue.

**Comment by ankitshaw** [comment]
@sanxy issue assigned.
@myselfanuj you have been assigned another issue

**Comment by myselfanuj** [comment]
@ankitshaw  Ok, but i want to work on this project properly. @sanxy if you aren't working on this issue please inform here.

**Comment by sumitsingh1698** [comment]
@ankitshaw i will like to work on it.

**Comment by neversettle17-101** [comment]
@ankitshaw I would like to work on it
