### ISSUE TITLE
Add panic button UI component

### ISSUE THREAD

**Issue by tanmayrauth** [CodingIndia/travel-safe#13]

**Comment by rohg007** [comment]
I would like to take up this issue

**Comment by ankitshaw** [comment]
@rohg007 you have been assigned the issue. Lets us know in case you have any doubts

**Comment by rohg007** [comment]
A bit more info, what are you looking for? A separate screen with a big panic button, or do I have to place a panic button in some existing screen?

**Comment by meghaa105** [comment]
I would like to help

**Comment by ankitshaw** [comment]
> A bit more info, what are you looking for? A separate screen with a big panic button, or do I have to place a panic button in some existing screen?

need only the UI component, so can be placed in separate screen.

**Comment by sanxy** [comment]
I will like to work on this issue if it becomes open

**Comment by ankitshaw** [comment]
Assigned to @meghaa105

**Comment by ankitshaw** [comment]
Hi @meghaa105  are you working on the issue?

**Comment by tanmayrauth** [comment]
We are closing this issue. Not needed anymore.
