### ISSUE TITLE
Panic button backed firebase integration

### ISSUE THREAD

**Issue by tanmayrauth** [CodingIndia/travel-safe#14]

**Comment by sanxy** [comment]
I will like to take up this issue, can the description be added

**Comment by myselfanuj** [comment]
I would like to work on it. I can implement an free sms alert service on panic button with location. Please assign me this issue so i can start work on it. @ankitshaw

**Comment by himanshusharma89** [comment]
I would like to work on this issue

**Comment by ankitshaw** [comment]
@himanshusharma89 assigned

**Comment by tanmayrauth** [comment]
@himanshusharma89 based on user when a person clicks on panic button for 3 times an entry for the same should be added to firebase object of user

This will be the first version. Further enhancement will raised as another issue.
