### ISSUE TITLE
Remove MapView Statements

### ISSUE THREAD

**Issue by rohg007** [CodingIndia/travel-safe#16]
Remove MapView statements causing problems in compilation of app.

**Comment by ankitshaw** [comment]
Can you please provide the link to the line no ?

**Comment by ankitshaw** [comment]
@tanmayrauth can you please look at this

**Comment by rohg007** [comment]
I guess it was line no. 2 and line no. 33, 34, 35 in main.dart

**Comment by sumitsingh1698** [comment]
error occuring in mapview statement @ankitshaw 
during compiling

**Comment by tanmayrauth** [comment]
Issue is fixed now
