### ISSUE TITLE
Add CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by Aman-Codes** [CodingIndia/travel-safe#29]
**Is your feature request related to a problem? Please describe.**
No CODE_OF_CONDUCT.md file is present.

**Describe the solution you'd like**
@tanmayrauth @ankitshaw  As a GSSOC participant I would like to add a CODE_OF_CONDUCT.md file in this project.

**Additional context**
### Screenshots

![code of conduct1](https://user-images.githubusercontent.com/54680709/77505634-beddc000-6e89-11ea-9dd5-f1e13ef6c6c9.PNG)
![code of conduct2](https://user-images.githubusercontent.com/54680709/77505638-c0a78380-6e89-11ea-8aa4-efcb21133da7.PNG)

**Comment by ankitshaw** [comment]
@Aman-Codes  go ahead

**Comment by Aman-Codes** [comment]
@ankitshaw Sir can you please share your email id which I can add in this file where participants can report any unacceptable behavior .

**Comment by ankitshaw** [comment]
codingindiaorg@gmail.com

**Comment by ankitshaw** [comment]
Hi @Aman-Codes your link to CODE OF CONDUCT was broken, please look into it ans raise a new PR

**Comment by Aman-Codes** [comment]
@ankitshaw Ok sir
