### ISSUE TITLE
Github Actions for monitoring 

### ISSUE THREAD

**Issue by HarshMehta2468** [CodingIndia/travel-safe#32]
I'd like to add the following github actions to this project:
1.)Greet:This action will greet the participant whenever they raise an issue or submit a PR .
2.)Stale: To mark unattended issues or PR(s).
3.)Mind-Your-Language: To warn the participant if he/she uses foul language in the reposiotry

Working on this ? Yes!

@ankitshaw Plz assign me this.

**Comment by prangya244** [comment]
I would like to work on this too.

**Comment by ankitshaw** [comment]
Hi, @mySTRiouscoder  what is the status?

**Comment by HarshMehta2468** [comment]
> Hi, @mySTRiouscoder what is the status?
Sent a PR
