### ISSUE TITLE
bug: component not able to run

### ISSUE THREAD

**Issue by 991rajat** [CodingIndia/travel-safe#33]
**Describe the bug**
The component is not able to run.
First, the bug was happening due to 
`<meta-data
    android:name="com.google.android.geo.API_KEY"
    android:value="<Your API Key" `/>`
'<' in value cannot appear in meta data .
 So I change it to the API key present in master. But still, the package is not able to run

**Screenshots**
![Screenshot (31)](https://user-images.githubusercontent.com/38184186/79042080-5d03b100-7c12-11ea-84f8-96a1e358e220.png)

**Comment by ankitshaw** [comment]
Issue is resolved
