### ISSUE TITLE
Create splash screen for the application

### ISSUE THREAD

**Issue by ankitshaw** [CodingIndia/travel-safe#4]
You need to create a splash screen for the application. It is the first screen that is visible to the used when he launches the app

**Comment by Rukmini-Meda** [comment]
I am interested to work on this issue. Please assign this to me as part of GSSoC'20.

**Comment by akshaydhiran** [comment]
I want to work on this issue.

**Comment by himanshusharma89** [comment]
I would like to work on this issue

**Comment by pa7ri** [comment]
Same here, I would like to work on it :)

**Comment by ankitshaw** [comment]
Hi @pa7ri, issue assigned.
@Rukmini-Meda @akshaysingh5 @himanshusharma89  you have been assigned another issues please check.

**Comment by OveeKulkarni** [comment]
I would like to work on this.

**Comment by ankitshaw** [comment]
@pa7ri are you still working on the issue?

**Comment by pa7ri** [comment]
Yes @ankitshaw, sorry for the delay I was managing to run a flutter app to check if it works

**Comment by payal-98** [comment]
Can I work on this issue?

**Comment by sanxy** [comment]
I will like to work on this issue if it becomes open

**Comment by pa7ri** [comment]
sorry for the delay but Im going to unassign myself, since I cant manage to run the project, good luck everyone

**Comment by sanxy** [comment]
I am available to take up the task
