### ISSUE TITLE
Create group User Interface

### ISSUE THREAD

**Issue by tanmayrauth** [CodingIndia/travel-safe#43]
User Interface which should allow user to create group and add members to that group

**Comment by akshaydhiran** [comment]
is it similar to like we have in the chat system app?

**Comment by bharatmk2567** [comment]
@akshaysingh5 it kinda create a group that we usually see in chat apps like WhatsApp, Telegram but we will going to use it as group location sharing

**Comment by sanxy** [comment]
I will like to work on this

**Comment by Rukmini-Meda** [comment]
@ankitshaw I would like to work on this issue. Please assign this to me as part of GSSoC'20.
