### ISSUE TITLE
Create group backend with firebase

### ISSUE THREAD

**Issue by tanmayrauth** [CodingIndia/travel-safe#44]
Logged in user should be able to create group and add members to that group.
All the group creation should be done by logged in users only.

**Comment by dwvicy** [comment]
Can I work on this?

**Comment by tanmayrauth** [comment]
@dwvicy Please let's finish the about us page assigned to you. Then you can pick this.

**Comment by sameeerkashyap** [comment]
Hello, I would like to work on this issue, please give me the specifics.
