### ISSUE TITLE
Add delete members from group ( UI and backend )

### ISSUE THREAD

**Issue by tanmayrauth** [CodingIndia/travel-safe#45]
User should be able to add and remove members from group.

**Comment by vipuldcoder** [comment]
I am interested with this issue, Can I work on this?

**Comment by tanmayrauth** [comment]
group creation is prerquisite for getting into this issue

**Comment by saloniankita** [comment]
Can I work on this issue @tanmayrauth ?
Please assign me this.

**Comment by tanmayrauth** [comment]
as mentioned above group creation is prerequisite for this. Would you like to work on that?

**Comment by saloniankita** [comment]
I can try @tanmayrauth
