### ISSUE TITLE
Currently shared location Screen (UI)

### ISSUE THREAD

**Issue by tanmayrauth** [CodingIndia/travel-safe#48]
An list UI with all the details about the users who have share. Similar to this.
Just develop a similar UI. Backed will be a different issue raised.
![image](https://user-images.githubusercontent.com/18233626/79636349-9a2ced80-8194-11ea-9915-a7be93dd35e2.png)

**Comment by himanshusharma89** [comment]
Hey @tanmayrauth can I work on it?

**Comment by ankitshaw** [comment]
Hi @himanshusharma89, assigned. Feel free to ask if you need more clarity at any point.

**Comment by tanmayrauth** [comment]
@himanshusharma89 were you able to make any progress?

**Comment by himanshusharma89** [comment]
Hey @tanmayrauth, I forgot to create the PR. I am creating it.

**Comment by TahaAli07** [comment]
@tanmayrauth I think this issue can be closed now,
