### ISSUE TITLE
Integrating Firebase Authentication to the app ( Backend )

### ISSUE THREAD

**Issue by ankitshaw** [CodingIndia/travel-safe#5]
You need to integrate firebase authentication to the application.
Also need to implement email verification.

**Comment by Samriddhi25** [comment]
I want to resolve this issue

**Comment by akshaydhiran** [comment]
I want to work on this issue.

**Comment by vineetjk** [comment]
Intrested

**Comment by myselfanuj** [comment]
I would like to work on it. I have great commands on firebase I already worked on firebase authentication for flutter. Please assign me this issue so i can start work on it. @ankitshaw

**Comment by ankitshaw** [comment]
@Samriddhi25 I have assigned you the issue. Let us know in case of any doubt.

**Comment by neversettle17-101** [comment]
I would also like to work on this issue. I have some experience regarding this before.

**Comment by OveeKulkarni** [comment]
I would like to work on this; could you assign it to me?

**Comment by tanmayrauth** [comment]
@OveeKulkarni PR has already been raised for this issue. Please take a look for other issues
