### ISSUE TITLE
Notification alert to member with whom location is shared

### ISSUE THREAD

**Issue by tanmayrauth** [CodingIndia/travel-safe#50]
If some logged in user has share his location to Mr XYZ then Mr XYZ should get a notification alert with long vibration. 

When Mr XYZ click on notification then maps ui should open he can see location of one who shared it.

**Comment by Rukmini-Meda** [comment]
I would like to work on this issue. Please assign this to me as part of GSSoC'20. I can work on 2 issues simultaneously. Please assign this and login backend to me after my PR of login ui is merged.

**Comment by tanmayrauth** [comment]
@Rukmini-Meda Please let's focus on the login. Don't worry there are many issues to be picked up. We won't be short of issues :)

**Comment by Rukmini-Meda** [comment]
@tanmayrauth @ankitshaw Shall I start working on this issue in the mean time my PR on login backend will be reviewed?
