### ISSUE TITLE
Splash screen UI

### ISSUE THREAD

**Issue by tanmayrauth** [CodingIndia/travel-safe#52]
a splash screen with inkling details about app 
Eg: https://www.androidhive.info/2016/05/android-build-intro-slider-app/

At last there will be signup and login page

**Comment by akshaydhiran** [comment]
I want to work on this issue and I mean it this time.

**Comment by ankitshaw** [comment]
Hi @akshaysingh5 issue #8 has already been blocked by you without any progress shown.

**Comment by akshaydhiran** [comment]
Sir, Will do it within a day for sure and seriously i really mean this time.

**Comment by sanxy** [comment]
I will like to work on this

**Comment by tanmayrauth** [comment]
Assigned to @sanxy please refer the above example and provide status update every 3-4 days

**Comment by sanxy** [comment]
Quick question, i did splash screen before which only shows when app starts for few seconds before proceeding to main screen. Do i override that or i should show the new UI after the previous splash screen? Kindly advice?

**Comment by tanmayrauth** [comment]
You can override that.
