### ISSUE TITLE
About Us UI activity

### ISSUE THREAD

**Issue by tanmayrauth** [CodingIndia/travel-safe#56]
**Aesthetically good** UI that provide details about

logo
Apps working 
Need of app
Mission of app
Contributor's list ( circular icon grid at the end of the above details, linked to their github account fetched from firebase db)

**Comment by akshaydhiran** [comment]
I really want to work on this issue.

**Comment by tanmayrauth** [comment]
Assigned. Make sure it is aesthetically good. Please do give status update after every 3 days.

**Comment by tanmayrauth** [comment]
Sorry @akshaysingh5 
Do complete your previous active issues. Then I will assign it to you.

**Comment by FrozenGirl-spd** [comment]
Can i work on this @tanmayrauth .. please..

**Comment by TahaAli07** [comment]
If anyone wants to take up this issue comment here or contact me. This involves building static pages and can be a beginner to intermediate level issue .

**Comment by FrozenGirl-spd** [comment]
Can I work on this?

**Comment by tanmayrauth** [comment]
Assigned. @ankitshaw Can you help her with some mock ui.

**Comment by ankitshaw** [comment]
![image](https://user-images.githubusercontent.com/25771394/80909092-100f8800-8d43-11ea-932e-7c1ac6d9c3b2.png)

Refer this image, as you will see.. The main page will have our icon and short slogan or motto provided to you. 
after that there will be different sections hidden Apps working, need of app,Mission of app,Contributor's list. Similar to version and advertise with us section. on clicking one section heading we will drop down to show details.
use cards and material layout to make this.
for the contributor's list section, when user clicks on the section. drop down and display small circular icons with github profile icon of the user on the circle and on clicking it open their github link.
we will use firebase for this. Let me know your gmail id I will provide you access to create table for this and use it for this issue. Thanks.

**Comment by ankitshaw** [comment]
Hi @FrozenGirl-spd, I hope the requirement is clear to you.

**Comment by FrozenGirl-spd** [comment]
Yep i get that.. bt the logo and content part, will i be adding on my own??
Is logo already there? or i need to prepare one..
Working prototype UX or just UI?
Any of the details can be shared to mail id.. 
priyadarshanisilla@gmail.com

**Comment by ankitshaw** [comment]
we need a working About us with backend (to make it dynamic). Let me know if you are comfortable with fetching from db and populating the text.

**Comment by FrozenGirl-spd** [comment]
Oops..i 've nt worked with backend stuffs :(

**Comment by dwvicy** [comment]
Can I work on this?

**Comment by TahaAli07** [comment]
Hi @dwvicy , Have you understood the requirements of this issue clearly , it will requiring both the front-end and back-end firebase part. If yes , We will assign you this issue.

**Comment by dwvicy** [comment]
Yes, I have!

**Comment by ankitshaw** [comment]
Hi @dwvicy, assigned you. Let us know if you need any help.

**Comment by Rukmini-Meda** [comment]
I would like to work on this issue. Please assign this to me as part of GSSoC'20.

**Comment by ankitshaw** [comment]
@Rukmini-Meda  assigned, Refer this comment https://github.com/codingindia/travel-safe/issues/56#issuecomment-623072658

**Comment by Rukmini-Meda** [comment]
> @Rukmini-Meda assigned, Refer this comment [#56 (comment)](https://github.com/codingindia/travel-safe/issues/56#issuecomment-623072658)

Okay
