### ISSUE TITLE
User Registration ( Backend )

### ISSUE THREAD

**Issue by tanmayrauth** [CodingIndia/travel-safe#58]
user registration form integrated with firebase db

**Comment by darkmatter18** [comment]
@tanmayrauth Assisn me please

**Comment by tanmayrauth** [comment]
We already have UI developed for this. @Rukmini-Meda I am assigning the backed part to @darkmatter18.

@pravinyo @ankitshaw  Can you guys elaborate over the implementation details to  @darkmatter18
