### ISSUE TITLE
User Login ( Backend )

### ISSUE THREAD

**Issue by tanmayrauth** [CodingIndia/travel-safe#59]
User authentication backend integration with UI

**Comment by himanshusharma89** [comment]
Can you suggest your desired UI?

**Comment by sanxy** [comment]
I will like to work on this

**Comment by tanmayrauth** [comment]
@Rukmini-Meda Is already working on the UI part. Let's wait for completion of that issue.

**Comment by Rukmini-Meda** [comment]
I would like to work on this issue. If its not assigned to anybody yet, please assign this to me after my PR on login UI is merged. Thank you.

**Comment by tanmayrauth** [comment]
@Rukmini-Meda It will be assigned to you since you have worked on the UI part of it.
@himanshusharma89 You are working on the location sharing section. I believe that will be consuming most of your time

**Comment by darkmatter18** [comment]
@tanmayrauth Can I work on it?

**Comment by bharatmk2567** [comment]
@darkmatter18 Currently you are working on  #58 once you've finished it we will assign it to you

**Comment by shwhite17** [comment]
can you please assign to me, I can make an animated login page in flutter if you provide stable logo #59 @tanmayrauth

**Comment by shwhite17** [comment]
@tanmayrauth

**Comment by tanmayrauth** [comment]
@darkmatter18 @shwhite17 @sanxy You guys can pick many other pending issues

**Comment by ankitshaw** [comment]
Hi @Rukmini-Meda, any blockers?

**Comment by Rukmini-Meda** [comment]
Had a few, but overcame them with help of @bharatmk257 and still working on it. Will make a PR by tomorrow night.

**Comment by bharatmk2567** [comment]
Hey @Rukmini-Meda Any status

**Comment by Rukmini-Meda** [comment]
@bharatmk257 Still working.... will try to complete it by today... sorry for being late...

**Comment by bharatmk2567** [comment]
No problem if you need any help slack it
