### ISSUE TITLE
Integration Map SDK to the application

### ISSUE THREAD

**Issue by ankitshaw** [CodingIndia/travel-safe#6]
You need to integrate google maps sdk to the application.
Create an activity that display the maps.

**Comment by infiniteoverflow** [comment]
I have worked on integrating google maps with flutter apps. I could work on it :)

**Comment by tanmayrauth** [comment]
Sure you can work on this. 
This issue is only related to integrating the maps sdk with flutter. Location tracking will be an another issue.

Add this feature in component directory please. Please do ask if you face any issue in understanding

**Comment by infiniteoverflow** [comment]
Okay sir  , so i juz need to implement a basic map on a screen?

**Comment by infiniteoverflow** [comment]
@tanmayrauth I have made the PR sir
