### ISSUE TITLE
Login Page resolution fix

### ISSUE THREAD

**Issue by ankitshaw** [CodingIndia/travel-safe#71]
**Describe the bug**
Login page height resolution issue with different devices

**To Reproduce**
1. use different resolution to check how ui behaves 

**Expected behavior**
the ui should be flexible based on any resolution

**Screenshots**
![](https://user-images.githubusercontent.com/15203737/80770716-e4c14900-8b48-11ea-95eb-192fe22db048.jpg)

**Comment by 991rajat** [comment]
I'll try to fix.

**Comment by ankitshaw** [comment]
Hi @991rajat , assigned to you. This issue is on priority so work accordingly.

**Comment by ankitshaw** [comment]
Hi @991rajat any update?

**Comment by ankitshaw** [comment]
```@override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("MediaQuery"),
      ),
      body: Container(
        width: MediaQuery.of(context).size.width * 0.5,
        height: MediaQuery.of(context).size.height * 0.5,
      ),
    );
  }
```
This is how to solve this.
In the `body: SingleChildScrollView` section of the login.dart file remove the `child: section` from there and then add  following inside the `child:container` after the `gradient:`
```
width: MediaQuery.of(context).size.width * 0.5,
height: MediaQuery.of(context).size.height * 0.5,
```

Let me know if you still face any issue! @991rajat

**Comment by ankitshaw** [comment]
Hi @TahaAli07  can you please help @991rajat with this. I have explained in short how to go about it ( see the above comment).
