### ISSUE TITLE
Enhance the Login Page

### ISSUE THREAD

**Issue by TahaAli07** [CodingIndia/travel-safe#72]
**Describe the bug**
REMOVE - 
OR 
Sign in with
The two logos
Shift the whole section at the center of the screen.
Put the sign up section at the bottom.
Change the logo with the new one in the .github/ directory

**Expected behavior**
Login Page UI should be according to the above directions.

**Comment by minolipvartak** [comment]
I am interested to work on this issue.

**Comment by akshaydhiran** [comment]
I want to work on this issue.

**Comment by TahaAli07** [comment]
I have assigned this to @akshaysingh5 . @minolipvartak Please go through all the issues and you want to work on any I will assign you that. 
You can also go through the app and suggest new issues and work on that.

**Comment by ankitshaw** [comment]
@TahaAli07 , there is update in this issue. We dont need "sign in with section any more". @akshaysingh5  please remove OR , sign in with and the two logos. And then shift the whole section at the center of the screen. 
and let the sign up section remain at the botton.
Also change the logo with the new one in the .github/ directory

**Comment by TahaAli07** [comment]
@ankitshaw I will create new issue for fixing the screen contents.

**Comment by akshaydhiran** [comment]
@ankitshaw Okay.

**Comment by TahaAli07** [comment]
@akshaysingh5 I have updated the issue description. You can work with the updated directions.
