### ISSUE TITLE
Main Screen Design

### ISSUE THREAD

**Issue by ankitshaw** [CodingIndia/travel-safe#77]
Create the Main screen layout for the application. 
Example:
![mockup2](https://user-images.githubusercontent.com/25771394/80993371-97025480-8e58-11ea-82ff-4f1555a98025.png)

Refer the above example as it is.
Tasks:
1. Create the logos. 
     a. The share logo
     b. Alert logo
2. Create bottom bar. This will be visible in all the screens. So you may have to keep it separatly
3. write the onclick code to launch another screen for all the logos and the bottom bar sections. Home button should take you again to the main screen. While mock the other buttons to take you to a blank screen with only the bottom bar.

**Comment by akshaydhiran** [comment]
i want to work on this issue.

**Comment by Ruchika30** [comment]
I can help if needed  @TahaAli07

**Comment by TahaAli07** [comment]
Hi @Ruchika30 and @akshaysingh5 , please work together on this issue . Keep this on a priority basis . Also message me if you face any issues.

**Comment by akshaydhiran** [comment]
Okay.

**Comment by sheen404** [comment]
Can I work on this issue?

**Comment by ankitshaw** [comment]
Hi @sheen404  assigned to you

**Comment by akshaydhiran** [comment]
70 % work is already done, just waiting for Ruchika's work @ankitshaw @TahaAli07.

**Comment by Ruchika30** [comment]
Yes. I would update my part of work by today. @TahaAli07  @ankitshaw

**Comment by sheen404** [comment]
@ankitshaw What should I do then?

**Comment by ankitshaw** [comment]
Hi @sheen404  work with akshay, the current PR raised by them are very basic, they will have to improve them. You can take up the improvement part. You need to use material design principle. @akshaysingh5 above image was just for reference, please take @sheen404  help and and make a aesthetic ui. Thanks

**Comment by akshaydhiran** [comment]
@ankitshaw Okay and @sheen404 contact us.

**Comment by akshaydhiran** [comment]
@sheen404 message on slack channel. So that we can reach out to you for further updates.
