### ISSUE TITLE
Create a activity with all the helpline info

### ISSUE THREAD

**Issue by ankitshaw** [CodingIndia/travel-safe#8]
You need to create a activity that lists all the helpline numbers like
1. Police 
2. Ambulance
3. Fire Brigade
4. Women's helpline no.
5. Railway help line number
so on and so forth

To make it dynamic. Fetch the details from firebase database. 
Use card layout and also allow user to directly call the helpline.

Refer below. On swipe left have a phone icon to call the contact
https://ibb.co/k3MLG2X

**Comment by akshaydhiran** [comment]
I want to work on this issue.

**Comment by sunchit17** [comment]
I want to work on this issue

**Comment by myselfanuj** [comment]
I would like to work on it. I used this type of feature in my project. Please assign me this  project so i can start my work @ankitshaw

**Comment by ankitshaw** [comment]
@akshaysingh5 Issue assigned.

**Comment by myselfanuj** [comment]
@akshaysingh5  If you aren't working on it please inform here.

**Comment by ankitshaw** [comment]
@akshaysingh5 are you still working on the issue?

**Comment by Akansha2202** [comment]
i would like to work on this issue

**Comment by sanxy** [comment]
I will like to work on this issue if it becomes open

**Comment by akshaydhiran** [comment]
> I will like to work on this issue if it becomes open

I am working on it.

**Comment by ankitshaw** [comment]
Hi @akshaysingh5   , the issue has been blocked for quite some time now.

**Comment by tanmayrauth** [comment]
@akshaysingh5 This issue has been assign to you more than a month back (4th March). I believe you are not showing any active contribution to it. Unfortunately we need to assign it to someone else if you fail to raise PR in next 1 day.

We can't block issues for other active contributors

**Comment by ankitshaw** [comment]
Remove assignee due to inactivity. Open for pick up

**Comment by sanxy** [comment]
I will like to work on this since its available

**Comment by tanmayrauth** [comment]
@sanxy Please let's finish the splash screen then you can pick this

**Comment by bharatmk2567** [comment]
@myselfanuj  would you like to work on this issue?

**Comment by ankitshaw** [comment]
@sunchit17 @himanshusharma89  anyone up for this?

**Comment by himanshusharma89** [comment]
> @sunchit17 @himanshusharma89 anyone up for this?

I can work on this. I'll update you if I face any issue

**Comment by ankitshaw** [comment]
Hi @himanshusharma89 assigned to you!

**Comment by tanmayrauth** [comment]
@ankitshaw can you provide @himanshusharma89  some mock UI
