### ISSUE TITLE
Add swiping left feature to intro page for better navigation of details of the application!

### ISSUE THREAD

**Issue by ibhanu** [CodingIndia/travel-safe#80]
By adding a gesture detector as follow
```
GestureDetector(onPanUpdate: (details) {
  if (details.delta.dy > 0) {
    // swiping in left direction
  }
});
```
and implement stack so that the next detail overlap the prev detail!

**Comment by namitamutha** [comment]
Please assign me this issue

**Comment by TahaAli07** [comment]
Hi @namitamutha as discussed I have assigned you this issue.

**Comment by TahaAli07** [comment]
@namitamutha What is the status of this issue ?

**Comment by shwhite17** [comment]
assign to me. @TahaAli07

**Comment by shwhite17** [comment]
@TahaAli07 tell me, gesture feature is added for android or for ios.

**Comment by TahaAli07** [comment]
@shwhite17 for both android and ios

**Comment by shwhite17** [comment]
@TahaAli07 , pull requested in dart language, review it.

**Comment by TahaAli07** [comment]
@shwhite17 I don't see any Pull request

**Comment by shwhite17** [comment]
@TahaAli07, I already pull requested once check it.

**Comment by TahaAli07** [comment]
@shwhite17 I see only 3 active PRs , can you check again on your side.

**Comment by shwhite17** [comment]
![Screenshot (53)](https://user-images.githubusercontent.com/57324656/82436867-1d06d800-9ab4-11ea-97c6-c8e1e08547fc.png)

check out this screenshot ?

**Comment by TahaAli07** [comment]
Hi @shwhite17 , you have committed the changes to your repository , this is not the way to create a PR . Please follow this video to create a PR - https://youtu.be/OVQK2zzb6U8

**Comment by sheen404** [comment]
Can I be assigned this issue?
