### ISSUE TITLE
README.md improvement

### ISSUE THREAD

**Issue by manxi** [CodingIndia/travel-safe#93]
It's well said " Don't Judge a book by it's cover" but still people judge others' project by looking to their README.md as it gives a permanent impression about the hard work we've done which is certainly not true

I'm Mansi and I write blogs & books. I'm good at content writing. I would like to contribute to the README.md file to make it better and enhance it's words and looks.

**Comment by manxi** [comment]
I request admins to assign this issue to me.

**Comment by tanmayrauth** [comment]
> I request admins to assign this issue to me.

Assigned to you. Please help us get the best version of it :)
